# Generated by Django 5.1.3 on 2024-12-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='is_active',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='status',
            field=models.IntegerField(choices=[('1', 'Pending'), ('2', 'Accepted'), ('3', 'Declined')], default=1),
        ),
    ]
