version: '3.10.12'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - vault
      - db
    environment:
      - VAULT_ADDR=http://vault:8200
    networks:
      - app-network
      
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  vault:
    image: hashicorp/vault
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_TOKEN}
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    command: server -dev
    networks:
      - app-network
    volumes:
      - vault_data:/vault/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  vault_data: