version: '3.10.12'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - web
    networks:
      - app-network

  web:
    build: .
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - vault
      - db
      - redis  # Add redis as a dependency
    environment:
      - VAULT_ADDR=http://vault:8200
      - DJANGO_SETTINGS_MODULE=djangoProject.settings
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  vault:
    image: hashicorp/vault
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_TOKEN}
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    command: server -dev
    networks:
      - app-network
    volumes:
      - vault_data:/vault/data

  redis:
    image: redis:6
    ports:
      - "6380:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  vault_data:
  static_volume:
