# Generated by Django 5.1.3 on 2025-01-17 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_tournamentgame_player_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentgame',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_games', to='tournaments.tournamentgame'),
        ),
    ]
