# Generated by Django 5.1.3 on 2024-12-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_playerprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerProfile',
        ),
    ]
