# Generated by Django 5.1.3 on 2024-12-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
