# Generated by Django 5.1.3 on 2025-01-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='total_points',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='elo',
            field=models.FloatField(default=1500),
        ),
    ]
