# Generated by Django 5.1.3 on 2025-01-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0002_remove_leaderboard_total_points_leaderboard_elo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='elo',
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterUniqueTogether(
            name='gamehistory',
            unique_together={('game_type', 'game_id')},
        ),
    ]
