# Generated by Django 5.1.3 on 2025-01-24 13:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchMaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='connected_players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
