# Generated by Django 5.1.3 on 2024-12-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_draws_userprofile_total_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='draws',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='match_history',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wins',
        ),
    ]
