# Generated by Django 5.1.3 on 2025-01-12 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one_score', models.IntegerField(blank=True, default=0, null=True)),
                ('player_two_score', models.IntegerField(blank=True, default=0, null=True)),
                ('winner_score', models.IntegerField(blank=True, default=0, null=True)),
                ('looser_score', models.IntegerField(blank=True, default=0, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('type_of_game', models.CharField(choices=[('multiplayer', 'Multiplayer'), ('solo_IA_easy', 'Solo IA Easy'), ('solo_IA_medium', 'Solo IA Medium'), ('solo_IA_hard', 'Solo IA Hard'), ('solo_player', 'Solo Player'), ('tournament', 'Tournament')], default='multiplayer', max_length=20)),
                ('looser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='looser_games', to='user.userprofile')),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_one_games', to='user.userprofile')),
                ('player_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_two_games', to='user.userprofile')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_games', to='user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SoloGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_solo_score', models.IntegerField(default=0)),
                ('IA_score', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('looser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='looser_games_solo', to='user.userprofile')),
                ('player_solo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_one_games_solo', to='user.userprofile')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_games_solo', to='user.userprofile')),
            ],
        ),
    ]
