# Generated by Django 5.1.3 on 2025-01-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_recorded_on_blockchain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
