# Generated by Django 5.1.3 on 2024-12-09 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_player_one_score_game_player_two_score'),
        ('user', '0003_remove_userprofile_draws_remove_userprofile_losses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='looser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='looser_games', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_one_games', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_two_games', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_games', to='user.userprofile'),
        ),
        migrations.CreateModel(
            name='SoloGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_solo_score', models.IntegerField(default=0)),
                ('IA_score', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('looser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='looser_games_solo', to='user.userprofile')),
                ('player_solo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_one_games_solo', to='user.userprofile')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_games_solo', to='user.userprofile')),
            ],
        ),
    ]
